In [1]:
import numpy as np

In [3]:
np.zeros((3))

array([0., 0., 0.])

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros((1,4))

array([[0., 0., 0., 0.]])

In [9]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [10]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.zeros((3,4), dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [12]:
np.zeros((3,4), dtype=str)

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [13]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
rand_array = np.random.random((2,4))
rand_array

array([[0.5759465 , 0.9292962 , 0.31856895, 0.66741038],
       [0.13179786, 0.7163272 , 0.28940609, 0.18319136]])

In [18]:
rounded_array = np.round(rand_array, 2)
rounded_array

array([[0.78, 0.17, 0.49, 0.81],
       [0.8 , 0.58, 0.87, 0.6 ]])

In [66]:
np.random.seed(10) # Призначаємо початкове зерно. Точка входу для псевдовипадкового алгоритмн
np.random.random((2,4))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071]])

In [221]:
np.random.randint(low=0, high=10, size=(5,5))

array([[0, 6, 2, 5, 9],
       [5, 5, 4, 1, 5],
       [9, 3, 0, 0, 5],
       [2, 7, 8, 8, 1],
       [5, 5, 1, 2, 5]], dtype=int32)

In [223]:
# same as random
np.random.seed(10)
np.random.uniform(size=(2,4))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071]])

In [224]:
# same as random
np.random.seed(10)
np.random.uniform(10.0, 50.0, size=(2,4))

array([[40.85282573, 10.83007797, 35.3459294 , 39.9521553 ],
       [29.94028049, 18.99186582, 17.92251459, 40.42122849]])