In [1]:
import numpy as np

In [4]:
first = np.array([[1,2,3], [4,5,6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
first.shape

(2, 3)

*2 рядки та 3 стовпця*

In [6]:
first.ndim

2

In [7]:
second = np.array([[7,8,9], [10,11,12]])
second

array([[ 7,  8,  9],
       [10, 11, 12]])

In [8]:
first + second

array([[ 8, 10, 12],
       [14, 16, 18]])

*поелементне складання двох масивів*

In [9]:
first + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [10]:
first - 2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [11]:
first * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [12]:
first / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [13]:
first // 2

array([[0, 1, 1],
       [2, 2, 3]])

In [14]:
first % 2

array([[1, 0, 1],
       [0, 1, 0]])

In [15]:
first ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [16]:
first ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [17]:
first

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
elem5 = first[1,1]
elem5

np.int64(5)

In [23]:
elem_5 = first[1][1]
elem_5

np.int64(5)

In [24]:
first[1,1] == first[1][1]

np.True_

Конкатенація за віссю 0

In [26]:
np.concatenate((first, second))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
np.concatenate((second, first))

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

Конкатенація за віссю 1

In [29]:
np.concatenate((first, second), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [30]:
np.concatenate((second, first), axis=1)

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

In [31]:
np.concatenate((np.array([10,20,30,40]), np.array([50,60,70,80])))

array([10, 20, 30, 40, 50, 60, 70, 80])